### ISSUE TITLE
Stream Alert Display Previous Stream's Title

### ISSUE THREAD

**Issue by JulianWebb** [techied/DoggoBot#1]
When posting the stream alert in the discord server today, doggoBot used the stream title from the previous stream "Run Died PepeHands" rather than the current stream title "100% Speedrun - !50FreeSubs".
![image](https://user-images.githubusercontent.com/471907/58364469-93550800-7e69-11e9-9187-13fd1a5b784e.png)

If I had to guess, it's a caching issue but I am not sure. I'd suggest switching to Webhooks from an API call so that the correct title is likely to be sent.

**Comment by techied** [comment]
No further issues noticed
